# 이 워크플로는 백엔드 코드 변경 시 실행된다.
name: Backend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'leavesback/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3 # 코드를 받아옴

      - name: Create .env file
        working-directory: ./leavesback
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env        # .env 파일 생성
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "SERVICE_ACCOUNT_KEY=${{ secrets.SERVICE_ACCOUNT_KEY }}" >> .env
          echo "LIVEBLOCKS_SECRET=${{ secrets.LIVEBLOCKS_SECRET }}" >> .env

      - name: Build Node.js image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/namunibs_node ./leavesback

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/namunibs_node
