name: Frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "leavesfront/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest # GitHub이 제공하는 Ubuntu 가상머신에서 실행된다.

    steps:
      - name: Checkout source
        uses: actions/checkout@v3 # GitHub Actions에서 코드를 받아온다

      - name: Set up Node.js
        uses: actions/setup-node@v3 # Node.js 환경을 세팅한다.
        with:
          node-version: "22.13.0"

      - name: Install dependencies & build
        working-directory: ./leavesfront # leavesfront 폴더에서 아래 명령 실행
        run: |
          npm install         # 의존성 설치
          npm run build       # 정적 파일 빌드 (결과물은 leavesfront/dist/에 위치)

      - name: Build nginx image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/namunibs_nginx ./leavesfront
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/namunibs_nginx
