name: Frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'leavesfront/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest # GitHub이 제공하는 Ubuntu 가상머신에서 실행된다.

    steps:
      - name: Checkout source
        uses: actions/checkout@v3 # GitHub Actions에서 코드를 받아온다

      - name: Build nginx image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/namunibs_nginx ./leavesfront
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/namunibs_nginx
